services:
  clickhouse:
    image: 'docker.io/clickhouse/clickhouse-server:23.4-alpine'
    container_name: clickhouse
    hostname: clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_SERVER_ID: 0
      CLICKHOUSE_SHARD: 0
      CLICKHOUSE_REPLICA: 0
      CLICKHOUSE_LOG_TO_CONSOLE: 1
      CLICKHOUSE_LOG_LEVEL: information
      CLICKHOUSE_LOG_QUERIES: 1
      CLICKHOUSE_LOG_QUERY_THREADS: 0
      CLICKHOUSE_LOG_QUERY_VIEWS: 0
    volumes:
      - ./config/clickhouse:/etc/clickhouse-server
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-log:/var/log/clickhouse-server
      - ./target/debug/clickhouse-udf-neo-top-k:/var/lib/clickhouse/user_scripts/clickhouse-udf-neo-top-k
      - ./target/debug/test:/var/lib/clickhouse/user_scripts/test
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE

volumes:
  clickhouse-data:
    name: "clickhouse-data"
  clickhouse-log:
    name: "clickhouse-log"